### Authentication
GET http://localhost:3000/auth/login
Content-Type: application/json
{
  "username": "logbookv1",
  "password": "logbookv1",
  "role":"admin"}
  
###
GET http://localhost:3000/admin/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOTE2ZjhhZC1kMGZiLTRiMjYtYmZiYS03YmZkNTg2NGZlYzciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzgyOTM1NDksImV4cCI6MTYzODI5Mzg0OX0.NQAKSHOFG-BwhLUtxRSUkbqKmHf_TRn5-2fXYOPAxzQ

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "role":"admin"
}

### Academic year
POST http://localhost:5000/api/academicyear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "academicyear": "2020-2021",
  "semester":"Semester 1"
}
###
GET http://localhost:5000/api/academicyear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "code": "React",
  "name": "React",
  "academictyear": "2020-2021",
  "school":"Tan Tao PMS"
}
###
PUT http://localhost:5000/api/academicyear/618d53e37af3fee179ecec6a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "code": "React",
  "name": "Test",
  "academicyear": "2020-2021",
  "school":"TPMS"
}
###
DELETE http://localhost:5000/api/academicyear/618dd13e0b0f280ca9539432
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs
###
{
  "code": "React",
  "name": "Test",
  "academicyear": "2020-2021",
  "school":"Tan Tao PMS"
}
### School
POST http://localhost:5000/api/school
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "name":"TanChanh1",
  "province": "Long AN",
  "district":"Duc Hoa",
  "town":"Hau Nghia"
}
###
GET http://localhost:5000/api/school
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

###
PUT http://localhost:5000/api/school/618dd2050b0f280ca953943a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "name":"TanChanh1",
  "province": "LongfsdfasdAN",
  "district":"Duc Hoa",
  "town":"Hau Nghia"
}
###
DELETE http://localhost:5000/api/school/618dd2050b0f280ca953943a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

### Student
POST http://localhost:5000/api/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "username": "giang12345",
  "password": "giang12345",
  "role":"student",
  "fullname":"Nguyen Tan Thanh Giang",
  "phone":"0364002059"}
###
GET http://localhost:5000/api/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

###
PUT http://localhost:5000/api/student/618ade4f5ca6709f6f477839
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhZTRiMjY5NDM5YWE1YjczMTM3NWYiLCJpYXQiOjE2MzY2NTE5MTZ9.9THydPGO8y3nap_iGFM2soKr-_KM5517zJMYlT_tsGs

{
  "username": "giang01",
  "password": "giang10",
  "role":"student",
  "fullname":"Nguyen Tan Thanh Giang",
  "phone":"0364002059"}
###  
DELETE  http://localhost:5000/api/student/618afc8e69439aa5b7313762
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhYzYyNmFmZmMxMjg1ODM3ZjgxNDIiLCJpYXQiOjE2MzY0ODc1NDl9.wVBFMhdAc1zsKgusibHFqSpidoab6JuPm2m6oNKzZzY