/** @format */
export const apiUrl =
  process.env.NODE_ENV !== "production"
    ? "http://localhost:3000"
    : "https://sleepy-inlet-56101.herokuapp.com/api";

export const SESSION_STORAGE_ACCESS_TOKEN_NAME = "access-token";
export const SESSION_STORAGE_REFRESH_TOKEN_NAME = "refresh-token";
// POST example
export const POSTS_LOADED_SUCCESS = "POSTS_LOADED_SUCCESS";
export const POSTS_LOADED_FAIL = "POSTS_LOADED_FAIL";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const FIND_POST = "FIND_POST";
// School
export const SCHOOLS_LOADED_SUCCESS = "SCHOOLS_LOADED_SUCCESS";
export const SCHOOLS_LOADED_FAIL = "SCHOOLS_LOADED_FAIL";
export const ADD_SCHOOL = "ADD_SCHOOL";
export const DELETE_SCHOOL = "DELETE_SCHOOL";
export const UPDATE_SCHOOL = "UPDATE_SCHOOL";
export const FIND_SCHOOL = "FIND_SCHOOL";
// Teacher
export const TEACHERS_LOADED_SUCCESS = "TEACHERS_LOADED_SUCCESS";
export const TEACHERS_LOADED_FAIL = "TEACHERS_LOADED_FAIL";
export const ADD_TEACHER = "ADD_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const FIND_TEACHER = "FIND_TEACHER";
// Student
export const STUDENTS_LOADED_SUCCESS = "STUDENTS_LOADED_SUCCESS";
export const STUDENTS_LOADED_FAIL = "STUDENTS_LOADED_FAIL";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const FIND_STUDENT = "FIND_STUDENT";
// COURSE
export const COURSES_LOADED_SUCCESS = "COURSES_LOADED_SUCCESS";
export const COURSES_LOADED_FAIL = "COURSES_LOADED_FAIL";
export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const FIND_COURSE = "FIND_COURSE";
// LESSON
export const LESSONS_LOADED_SUCCESS = "LESSONS_LOADED_SUCCESS";
export const LESSONS_LOADED_FAIL = "LESSONS_LOADED_FAIL";
export const ADD_LESSON = "ADD_LESSON";
export const DELETE_LESSON = "DELETE_LESSON";
export const UPDATE_LESSON = "UPDATE_LESSON";
export const FIND_LESSON = "FIND_LESSON";
// Class
export const CLASSES_LOADED_SUCCESS = "CLASSES_LOADED_SUCCESS";
export const CLASSES_LOADED_FAIL = "CLASSES_LOADED_FAIL";
export const ADD_CLASS = "ADD_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const FIND_CLASS = "FIND_CLASS";
// Timetable
export const TIMETABLES_LOADED_SUCCESS = "TIMETABLES_LOADED_SUCCESS";
export const TIMETABLES_LOADED_FAIL = "TIMETABLES_LOADED_FAIL";
export const ADD_TIMETABLE = "ADD_TIMETABLE";
export const DELETE_TIMETABLE = "DELETE_TIMETABLE";
export const UPDATE_TIMETABLE = "UPDATE_TIMETABLE";
export const FIND_TIMETABLE = "FIND_TIMETABLE";
export const MATRIX_TIMETABLES_LOADED_SUCCESS =
  "MATRIX_TIMETABLES_LOADED_SUCCESS";
// Logbook
export const LOGBOOKS_LOADED_SUCCESS = "LOGBOOKS_LOADED_SUCCESS";
export const LOGBOOKS_LOADED_FAIL = "LOGBOOKS_LOADED_FAIL";
export const ADD_LOGBOOK = "ADD_LOGBOOK";
export const DELETE_LOGBOOK = "DELETE_LOGBOOK";
export const UPDATE_LOGBOOK = "UPDATE_LOGBOOK";
export const FIND_LOGBOOK = "FIND_LOGBOOK";
// User
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const UPDATE_USER = "UPDATE_USER";
